//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPILab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        public string Name { get; set; }
        public string Category { get; set; }
        public Nullable<int> Rating { get; set; }
        public string ImgSrc { get; set; }
    }
}
